Kinvey/kinvey-cli

CHANGELOG.md, LICENSE.txt, lib/datalink.coffee, lib/init.coffee, lib/project.coffee, lib/request.coffee, lib/user.coffee, lib/util.coffee, package.json, test/cli.coffee, test/project.coffee, test/user.coffee
This PR will prompt the user to re-authenticate upon `InvalidCredentials` errors. It also updates several dependencies in `package.json`.
=> BACK-938: Renew expired tokens.

.gitignore, package.json
- Updated archiver.js to version 1.0.1 to support node 6.x
=> BACK-1577: Add node.js 6.x support

README.md, cmd/deploy.coffee, cmd/job.coffee, cmd/logs.coffee, cmd/recycle.coffee, cmd/status.coffee, config/default.coffee, lib/datalink.coffee, lib/error.coffee, lib/project.coffee, lib/prompt.coffee, lib/service.coffee, package.json, test/datalink.coffee, test/deploy.coffee, test/job.coffee, test/logs.coffee, test/project.coffee, test/recycle.coffee, test/status.coffee
Refactored DLC-CLI to Kinvey-CLI. In addition to this PR, the 'Kinvey/dlc-cli' repository must be renamed and the npm project renamed/re-created.
=> BACK-1853 'Kinvey-CLI' rebrand

lib/datalink.coffee, test/datalink.coffee
=> BACK-1836: Modify logs command to display log threshold (if it exists)

README.md, cmd/config.coffee, cmd/logs.coffee, lib/error.coffee, lib/project.coffee, lib/prompt.coffee, lib/service.coffee, lib/user.coffee, lib/util.coffee, package.json, test/config.coffee, test/logs.coffee, test/service.coffee, test/user.coffee
* 'logs' command now takes optional 'to'/'from' parameters instead of prompting for them
=> BACK-2036: Refactor 'logs' command

lib/user.js, test/user.js
- Fix crash on 2FA login
- CLI no longer retries with prompt when auth fails via username/password supplied as opts
=> BACK-2703: Fix 2FA login crash

lib/CLIManager.js, lib/CommandResult.js, lib/Constants.js, lib/flex/FlexController.js, lib/flex/FlexService.js, lib/init/InitController.js, lib/profile/ProfilesController.js
* Enable `--output` option providing JSON support
* Improve human-readable output
**Note:** Tests will be fixed/added before merging base branch (output-improvements) into a release branch. Same applies for TODOs related to this ticket (cli-28).
=> CLI-28: Enable json output; improve human-readable output

__snapshots__/app-show.test.js, __snapshots__/org-show.test.js, __snapshots__/profile-delete.test.js, lib/Utils.js, lib/profile/ProfilesController.js, lib/profile/profilesRouter.js, test/integration/commands/profile/profile-delete.test.js
Use the active profile (if set) if no profile name is supplied for `kinvey profile delete`
=> Cli 52 use active profile

__snapshots__/env-delete.test.js, __snapshots__/profile-show.test.js, lib/environment/EnvironmentsController.js, lib/profile/ProfilesController.js, test/integration/commands/environment/env-delete.test.js, test/integration/commands/profile/profile-show.test.js
Show properly profile details if active items are set
Clear active env on 'env delete'
=> Cli 57 remove active env on delete

__snapshots__/schema-validator.test.js, lib/EnvFileProcessor.js, lib/SchemaValidator.js, test/fixtures/config-files/env-invalid.json, test/fixtures/config-files/env-valid-all-options.json
Move scheduling of endpoints from first-level property ('scheduledCode') to second-level 'schedule' property in 'endpoints'
=> CLI-91: Move scheduled endpoints to endpoints

__snapshots__/flex-logs.test.js, lib/flex/FlexService.js, test/fixtures/logs.json
Show properly logs when the logged message is actually an object.
=> Cli 111 flex logs object

__snapshots__/flex-status.test.js, lib/Constants.js, lib/Utils.js, lib/flex/FlexService.js, test/fixtures/datalinks-status-response.json, test/integration/commands/flex/flex-status.test.js, test/mockServer.js
The deployment status will be shown when `flex-operator` feature falg is enabled for application
Flex status command output
```
key                value                                
-----------------  -------------------------------------
status             ONLINE                               
version            1.4.2                                
runtime            FLEX-RUNTIME-NODE8                   
id                 123456                               
requestedAt        replaced_value
deployerEmail      davy.jones@mail.com                  
deployerName       Davy Jones                           
deploymentStatus   COMPLETED                            
deploymentVersion  1.4.2                                
deploymentRuntime  FLEX-RUNTIME-NODE10  
```
=> Flex-198: Extended flex status command to show deployment information

__snapshots__/env-create.test.js, __snapshots__/env-delete.test.js, __snapshots__/env-list.test.js, __snapshots__/env-show.test.js, __snapshots__/env-use.test.js, lib/Constants.js
Rename the environment namespace from 'env' to 'appenv'
=> CLI-125: Rename env namespace to appenv

__snapshots__/app-create.test.js, lib/CLIManager.js, lib/application/ApplicationsController.js, lib/application/applicationsRouter.js, test/integration/commands/application/app-create.test.js
Add functionality to create an app inside an organization through the `org` option
=> CLI-137: Add org option to app create

lib/BusinessLogicService.js, test/ConfigManagementHelper.js, test/integration-no-mock/config-management/env-config-create.js, test/integration-no-mock/config-management/env-config-push.js
Increased requests timeout for endpoints-related requests
Increased tests timeouts for environments that contain endpoints
=> Cli 134 fix tests failures

__snapshots__/app-create.test.js, __snapshots__/schema-validator.test.js, lib/AppFileProcessor.js, lib/CLIManager.js, lib/ConfigFileProcessor.js, lib/Constants.js, lib/EnvFileProcessor.js, lib/FileProcessorHelper.js, lib/SchemaValidator.js, lib/application/ApplicationsController.js, lib/application/ApplicationsService.js, lib/application/applicationsRouter.js, lib/exporter/AppFileExporter.js, test/ApiService.js, test/ConfigManagementHelper.js, test/fixtures/config-files/app-invalid.json, test/fixtures/config-files/app-valid-all-options.json, test/integration-no-mock/config-management/app-config-create.js, test/integration-no-mock/config-management/app-config-push.js, test/integration-no-mock/config-management/config-management.test.js, test/unit/lib/schema-validator.test.js
Handling app config files for create and push
Doesn't work with services
=> Cli 123 app config create and push

__snapshots__/common.test.js, __snapshots__/env-delete.test.js, __snapshots__/env-show.test.js, __snapshots__/flex-deploy.test.js, __snapshots__/flex-logs.test.js, __snapshots__/flex-recycle.test.js, __snapshots__/flex-status.test.js, lib/Constants.js, lib/application/applicationsRouter.js, lib/environment/environmentsRouter.js, lib/flex/FlexController.js, lib/flex/flexRouter.js, lib/organization/organizationsRouter.js, test/integration/commands/application/app-delete.test.js, test/integration/commands/application/app-show.test.js, test/integration/commands/environment/env-delete.test.js, test/integration/commands/environment/env-show.test.js, test/integration/commands/flex/flex-delete.test.js, test/integration/commands/flex/flex-logs.test.js, test/integration/commands/flex/flex-recycle.test.js, test/integration/commands/flex/flex-status.test.js, test/integration/commands/organization/org-show.test.js
Accept entity identifiers as options instead of positional args
Rename flex serviceId option to service
=> Cli 157 entity identifiers as options

lib/AppFileProcessor.js, lib/EnvFileProcessor.js, test/ConfigManagementHelper.js, test/integration-no-mock/config-management/app-config-create.js
Rework creating an app from a config file in order to work fine for users with plan restrictions
Note: Probably, should be reviewed after PR #136 is merged.
=> Cli 156 rework for plan restrictions

__snapshots__/common.test.js, lib/application/applicationsRouter.js, lib/environment/environmentsRouter.js, lib/organization/organizationsRouter.js, lib/service/ServicesController.js, lib/service/servicesRouter.js, test/ConfigManagementHelper.js, test/integration-no-mock/config-management/app-config-create.js, test/integration-no-mock/config-management/app-config-push.js, test/integration-no-mock/config-management/env-config-create.js, test/integration-no-mock/config-management/env-config-export.js, test/integration-no-mock/config-management/env-config-push.js
Adjust entity identifiers to be specified as options instead of pos args (cli-157). This has already been done in master but here there are some new commands. Adjust tests.
=> Adjust entity identifiers; update tests

__snapshots__/schema-validator.test.js, lib/Constants.js, lib/SchemaValidator.js, lib/ServiceFileProcessor.js, lib/exporter/ServiceFileExporter.js, lib/flex/flexRouter.js, test/ConfigManagementHelper.js, test/fixtures/config-files/flex-internal-invalid.json, test/fixtures/config-files/flex-internal-valid-all-options.json, test/integration-no-mock/config-management/app-config-export.js, test/integration-no-mock/config-management/org-config-export.js, test/integration-no-mock/config-management/service-config-create.js, test/integration-no-mock/config-management/service-config-export.js, test/integration-no-mock/config-management/service-config-push.js
Support runtime and environmentVariables
Add a test for flex service config file without service environments
=> Cli 166 support runtime env vars

lib/AppFileProcessor.js, test/ConfigManagementHelper.js, test/integration-no-mock/config-management/app-config-push.js
Fix `app push` to update environment metadata (e.g. collections)
=> Cli 171 fix app push

README.md, __snapshots__/common.test.js, __snapshots__/website-publish.test.js, __snapshots__/website-show.test.js, __snapshots__/website-unpublish.test.js, config/default.js, lib/Constants.js, lib/Utils.js, lib/website/SiteEnvsService.js, lib/website/SitesController.js, lib/website/SitesService.js, lib/website/sitesRouter.js, test/fixtures/site-envs-one.json, test/fixtures/sites.json, test/integration/commands/website/website-publish.test.js, test/integration/commands/website/website-unpublish.test.js, test/mockServer.js
* Adjust existing websites commands
* Add commands: 
`kinvey website publish (--website <website-id-or-name>) (--domainName <domain-name>)`
`kinvey website unpublish (--website <website-id-or-name>)`
=> META-296: Website publish/unpublish

lib/Request.js, test/ApiService.js, test/unit/lib/request.test.js
Fix slashes when services run on localhost
=> Meta 293 fix baas host

__snapshots__/flex-logs.test.js, __snapshots__/flex-status.test.js, __snapshots__/flex-update.test.js, lib/Constants.js, lib/flex/FlexService.js, test/fixtures/datalinks-status-response.json, test/fixtures/svc-envs-several.json, test/integration/commands/flex/flex-status.test.js
* Add new flex statuses: `Building`, `Deploying`
* Output any status in upper case
=> META-319: Add flexibility when handling flex status

README.md, __snapshots__/website-create.test.js, __snapshots__/website-show.test.js, lib/Constants.js, lib/Utils.js, lib/website/SiteEnvsService.js, lib/website/SitesController.js, lib/website/sitesRouter.js, package.json, test/fixtures/site-env-body.json, test/fixtures/site-envs-one.json, test/integration/commands/website/website-create.test.js, test/mockServer.js
* Allow specifying routing and pages on `website create`:
`kinvey website create <name> [--historyApiRouting|--errorPage=<error-page>] [--indexPage=<index-page>]`
* Show routing and pages on `website show`
=> META-328: Add pages and routing

README.md, __snapshots__/website-create.test.js, __snapshots__/website-list.test.js, __snapshots__/website-show.test.js, lib/CLIManager.js, lib/Constants.js, lib/website/SitesController.js, lib/website/sitesRouter.js, test/fixtures/sites.json, test/integration/commands/website/website-create.test.js, test/integration/commands/website/website-show.test.js
`website create` - require app or org
`website list` - show only ID + name
`website show` - show app or org
Note: Should be merged and published after the backend is deployed.
=> Meta 327 sites linked to apps

lib/service/ServicesService.js
Filter services to get only these that are 'attached' to the specified app.
=> META-406: Filter services to get only app level ones

lib/website/SiteEnvsService.js, lib/website/SitesController.js, test/unit/lib/site-envs-service.test.js
Validate the files size on `website deploy` before sending the request to the backend.
=> META-359: Validate files size when deploying sites

README.md, __snapshots__/app-create.test.js, __snapshots__/common.test.js, __snapshots__/env-create.test.js, lib/Constants.js, lib/application/applicationsRouter.js, lib/environment/environmentsRouter.js, lib/organization/organizationsRouter.js, lib/service/servicesRouter.js, package.json, test/ConfigManagementHelper.js
Specify path to configuration file as an option instead of as a positional argument.
=> META-419: Move file from positional argument to option

lib/CLIManager.js, lib/init/InitController.js, test/mockServer.js
* Adjust to the identity providers API changes
* Fix login with 2fa bug
=> KDEV-1062: KDEV-1061: Adjust to API changes; fix login options

__snapshots__/schema-validator.test.js, lib/Constants.js, lib/SchemaValidator.js, test/ConfigManagementHelper.js, test/fixtures/config-files/env-invalid.json, test/fixtures/config-files/env-valid-all-options.json, test/integration-no-mock/config-management/env-config-create.js
* Allow new login hooks only for `user` collection.
* Updated unit and integration tests
=> KDEV-1570: Support for login hooks
