CHANGELOG.md
cmd/config.coffee
cmd/deploy.coffee
cmd/list.coffee
cmd/recycle.coffee
cmd/status.coffee
lib/datalink.coffee
lib/project.coffee
package.json
test/datalink.coffee

Updates deploy, recycle, and status routes to use MAPI /jobs endpoint.
NOTE: Make sure release of MAPI is timed with npm publish of dlc-cli.

[BACK-905] Refactor routes.

---

lib/datalink.coffee

When retrieving a deploy status, display the latest progress message together with the status. This will also cause error messages to be displayed whenever a task is marked as `FAILED`.

BACK-1307: DLC error handling

---

CHANGELOG.md
lib/datalink.coffee
lib/util.coffee
package.json

This PR fixes a bug in the deploy functionality where deploying would fail if the user was not authenticated properly. Due to the project package being pipe-d into the request, the default retry functionality did not work properly. The changes here manually handle authentication errors, so retrying a deploy actually works.

BACK-1325: Handle authentication errors when deploying.

---

README.md
bin/cli.coffee
cmd/logout.coffee
config/default.coffee
lib/init.coffee
lib/project.coffee
lib/user.coffee
lib/util.coffee
test/cli.coffee
test/config.coffee
test/logout.coffee
test/logs.coffee
test/project.coffee
test/user.coffee

*`host` is no longer manually required on a per-call basis when the CLI is initialized via  `config [host]`
*Added `logout` command to easily clear session and project data
*Kinvey CLI now supports persistent tokens for multiple hosts. Users are only re-prompted for credentials when tokens expire or when logging into a new host for the first time
*The default host (manage.kinvey.com) is used when `-e` and `-p` are specified without a corresponding `--host` arg
... plus tests

BACK-1912: Kinvey CLI usability enhancements

---

README.md
bin/cli.coffee
cmd/config.coffee
cmd/logout.coffee
config/default.coffee
lib/init.coffee
lib/project.coffee
lib/user.coffee
lib/util.coffee
test/cli.coffee
test/config.coffee
test/logout.coffee
test/logs.coffee
test/project.coffee
test/user.coffee

It previously (only) loaded the contents of '.kinvey'. All other commands perform as they did before, i.e. they will only prompt for settings if a project is not configured or a user is not logged in

BACK-1849: 'config' command now forces prompt to select a new project

---

cmd/config.coffee
lib/error.coffee
lib/project.coffee
lib/user.coffee
lib/util.coffee
package.json
test/config.coffee
test/user.coffee

* `config test` now attempts to configure the CLI using `https://test-manage.kinvey.com`
* HTTP or HTTPS URLs are left in-tact

BACK-1934: Obfuscate Kinvey MAPI URLs. Plus tests.

---

cmd/config.coffee
lib/error.coffee
lib/init.coffee
lib/project.coffee
lib/user.coffee
test/config.coffee
test/user.coffee

Addressed a bug where 'ProjectNotConfigured' was not displayed when attempting to run a command against the default instance while unauthenticated.

BACK-2060: Fix CLI 'ProjectNotConfigured' bug

---

README.md
lib/error.coffee
lib/project.coffee
lib/prompt.coffee
test/fixtures/org.json
test/project.coffee

Sample output and example of new flow:
```Sams-MacBook-Pro:basicDlc sam$ cli.js config http://localhost:8888
info:  host: http://localhost:8888/
? E-mail sam@kinvey.com
? Password ********
info:  Welcome back sam@kinvey.com
? Would you like to select a service from a Kinvey app or org? Organization
? Which org would you like to use? my-org
? Which service would you like to use? my-link
Sams-MacBook-Pro:basicDlc sam$ cli.js status
info:  host: http://localhost:8888/
info:  Service status: NEW
Sams-MacBook-Pro:basicDlc sam$```

BACK-1883: Add support for choosing services from an organization 

---

lib/service.coffee
package.json
test/service.coffee

This PR adds two features surrounding logging:
- Stringify log messages that are not previously stringified server-side
- When processing and printing server-side log results, skip messages (and add trace code for this when CLI is run in verbose mode) when `message` property is missing

BACK-2190: Add protection for parsing/displaying malformed FSR log messages

---

lib/project.coffee
test/project.coffee

Fixed a bug in the `list` command which was introduced when support was added for org-backed datalinks. Plus tests.

BACK-2204: Fix `list` command bug (and adjust tests)

---

lib/user.coffee
lib/util.coffee
test/user.coffee

Fix bug where CLI errors when running `kinvey config` and the session file does not exist

BACK-2440: Set default host when config file does not exist

---

lib/user.coffee
test/user.coffee

`this.host` is set (prior to invocation of `restore`) if a custom instance is specified in the `config` command. This branch fixes a bug where the instance was set to default even if an override existed. Includes a test.

BACK-2575: Fix bug where instance override was not honored

---

lib/prompt.js
lib/user.js
test/mocha.opts
test/prompt.js
test/user.js

Adds 2FA support to the Kinvey CLI. If an login request succeeds with a set of credentials but is rejected due to an invalid 2FA token, the error is suppressed and a prompt is displayed for a token. This token is included with the original credentials on the second login attempt.

BACK-2644: Add 2FA support

---

cmd/logs.js
config/default.js
lib/constants.js
lib/error.js
lib/service.js
lib/util.js
test/cmd/logs.test.js
test/fixtures/command.js
test/lib/service.test.js

- Adds `--start` and `--end` flags (which replace) `kinvey logs [from] [to]` optional method params
- Adds `--number`/`-n` option for specifying number of entries to return (default = 100, max = 2500)
- Adds `--page` option for viewing logs in pages (of size `-n`)
... plus tests

BACK-2804: Initial refactor of logs command

---

cmd/config.js
cmd/logs.js
config/default.js
lib/constants.js
test/cmd/logs.test.js

This branch gracefully handles the deprecation of `[from] [to]` parameters (as part of the transition to `--from --to` flags in version 2.0).
* Added `from` and `to` args back to the `logs` command function to prevent the CLI from crashing if legacy users try to filter logs using the deprecated parameters
* CLI throws an error instructing users to use the new command format when either deprecated param is used
* Added tests

BACK-2804: Error out if deprecated 'from' and/or 'to' params are provided to 'logs' cmd

---

lib/service.js
test/integration/status.test.js
test/unit/lib/service.test.js

Enhances the `status` command to show the deployer email address (and first/last name, if set) and the formatted date/time of the most recent deploy. Plus tests.

BACK-2580: Show who deployed latest Flex service and when

---

package.json

Update some dev dependencies. The only one expected to not pass the security check is 'suppose' package ('string' dependency): https://www.npmjs.com/advisories/536. There's no version to update to but at the same time the vulnerability doesn't really concern us.

CLI-149: Update nyc and snap-shot-it

---

__snapshots__/app-create.test.js
__snapshots__/coll-create.test.js
__snapshots__/coll-delete.test.js
__snapshots__/coll-list.test.js
__snapshots__/common.test.js
__snapshots__/env-create.test.js
__snapshots__/env-delete.test.js
__snapshots__/env-list.test.js
__snapshots__/env-show.test.js
__snapshots__/env-use.test.js
__snapshots__/flex-clear.test.js
__snapshots__/flex-create.test.js
__snapshots__/flex-deploy.test.js
__snapshots__/flex-job.test.js
__snapshots__/flex-list.test.js
__snapshots__/flex-logs.test.js
__snapshots__/flex-recycle.test.js
__snapshots__/flex-status.test.js
__snapshots__/flex-update.test.js
__snapshots__/profile-create.test.js
lib/CLIManager.js
lib/Constants.js

Add aliases for the following options:
- `instance-id` = `instanceId`
- `no-prompt` = `noPrompt`
- `no-color` = `noColor`
- `suppress-version-check` = `suppressVersionCheck`
Without these aliases and when `camel-case-expansion` is false, these options cannot be set as environment variables. The CLI errors out because yargs parses them to camel case but then it can't recognize them.

Add camel case aliases for long options

---

lib/flex/FlexController.js

Preserve existing env vars on `flex deploy --set-vars <env-vars-to-set>`.

CLI-165: Fix env vars on deploy

---

lib/exporter/AppFileExporter.js
lib/service/ServicesService.js
test/ConfigManagementHelper.js
test/integration-no-mock/config-management/app-config-export.js
test/integration-no-mock/config-management/config-management.test.js

Test 'app export'
Fix 'app export' to export only app-owned services
*Note:* Branch based on 'cli-138-v3-api-migration-ea-config'. Should be reviewed after PR #150 gets merged.

Cli 136 test app export

---

lib/Constants.js
lib/website/SiteEnvsService.js
lib/website/SitesController.js
lib/website/sitesRouter.js
test/unit/lib/site-envs-service.test.js

`website deploy`
Validate that indexPage and errorPage are actually present in the files that are about to be uploaded. 
Return error if not. Error example: 
`[error] PagesNotFound: One or more pages not found. Index page: 'index.html'. Error page: 'error.html'.`
Add a `--force` flag to the command. Default value: `false`. On `website deploy --force` pages validation is skipped.

META-346: Validate pages on deploy; add force flag

---

lib/Request.js
test/unit/lib/request.test.js

When response is 4xx sometimes there's a `debug` property that contains more info. It is a string in most cases, but it could also be an instance of Error or just an object.

META-164: Improve error response handling

---

README.md
__snapshots__/app-create.test.js
__snapshots__/env-create.test.js
__snapshots__/flex-create.test.js
__snapshots__/flex-list.test.js
__snapshots__/org-show.test.js
__snapshots__/org-use.test.js
__snapshots__/schema-validator.test.js
__snapshots__/website-create.test.js
lib/Constants.js
lib/SchemaValidator.js
lib/application/applicationsRouter.js
lib/environment/environmentsRouter.js
lib/exporter/AppFileExporter.js
lib/exporter/OrgFileExporter.js
lib/exporter/ServiceFileExporter.js
lib/organization/OrganizationsService.js
lib/service/servicesRouter.js

The PR contains several small fixes and improvements for the GA release of the Config management feature:
* Allow creating app, app env or service with a name that contains only digits
* Do not export the `serviceEnvironment` field on the serviceObject during `service export`
* Fetch all orgs that a user can read
* Do not export services of type `custom`
* Remove support for SAP services as they are deprecated

Fix small config management bugs

---

README.md
__snapshots__/schema-validator.test.js
lib/Constants.js
test/fixtures/config-files/rapid-data-sp-invalid-some-options.json
test/fixtures/config-files/rapid-data-sp-invalid.json
test/fixtures/config-files/rapid-data-sp-valid-some-options.json
test/integration-no-mock/config-management/service-config-apply.js
test/integration-no-mock/config-management/service-config-create.js
test/integration-no-mock/config-management/service-config-export.js

Rename RapidData services to `data-X`. 
Example: `sharepoint` to `data-sharepoint`.

Improve service type names

---

lib/Utils.js

This converts the allowed lengths to a list and checks that the provided environment ID's length matches one of the allowed lengths.
Fixes https://github.com/Kinvey/kinvey-cli/issues/195

Fix NotFound error with 12 character long Env ID

---

lib/EnvFileProcessor.js

* Do not update the env when the `settings` field is missing from the config file on `kinvey appenv apply`.

KDEV-1157: Do not update the env if no settings

---

lib/Constants.js
lib/RolesService.js
package.json
test/ApiService.js
test/fixtures/config-files/env-valid-all-options.json
test/integration-no-mock/config-management/org-config-apply.js

1) Added missing collection hook types as they resulted in ValidationError when trying to create/modify those collection hook types.
2) Updated to use recommended _Buffer.from()_ constructor to fix:
`DeprecationWarning: Buffer() is deprecated due to security and usability issues when I move my script to another server`

KDEV-1308: Fix Validation error for collection hooks
